[package]
name = "stq_routes"
version = "0.1.0"

[dependencies]
enum-iter = { git = "https://github.com/StoriqaTeam/enum-iter" }
juniper = "0.9.2"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "*", features = ["serde"] }
